modLoader="javafml"
loaderVersion="[36,)"
license="All rights reserved"
[[mods]] #mandatory
modId="bh3"
version="1.16.5-0.0.1"
displayName="BH3"
authors="yuo"
logoFile="bh3rd.png"
description='''
崩坏三。1.16.5
'''